server:
  port: 40001

run:
  schedule: false  # 设置为 true 以启动定时任务，设置为 false 则不运行
  oldDataSynchronizeStatus: false  # 开启旧系统同步
  checkLivingStatusScan: false  # 开启直播状态

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  redis:
    host: 116.205.190.9
    port: 6379
    password: 12345A
  # rabbitmq
  rabbitmq:
    host: 139.159.132.31
    port: 5672
    username: rabbitmq
    password: password
    queue1: data_synchronize_test
    queue2: test1_test
    queue3: data_export_test
    queue4: data_export2_test
    queue5: data_synchronize_test_timeout_test
    queue6: data_upload_test

  data:
    mongodb:
      username: scnuAdmin
      password: scnu2023
      authentication-database: scnuXueli
      database: scnuXueli
      host: 139.159.132.31
      port: 27017
      auto-index-creation: true

  servlet:
    multipart:
      maxFileSize: 10GB
      maxRequestSize: 10GB
  ## mysql
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://113.108.140.172:3308/adult_education_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xhl2023@
    hikari:
      maximum-pool-size: 1000 # 设置最大连接数为1000
      idleTimeout: 300000  # set to 5 minutes for example

#配置日志
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*xml
  type-aliases-package: com.scnujxjy.backendpoint.dao.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出到控制台
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 使用 SLF4J 和 Logback

# 设置日志输出
logging:
  config: src/main/resources/logback.xml


minio:
  url: http://124.71.34.208:9000/
  accessKey: 3FMLUJWXYWY185YOGG2B
  secretKey: u+Leg+yN0jgRd+7xCEbLMUhSHoyKQjYBeZ4kYD9J
  bucketName: xuelistudentpictures
  courseCoverDir: xueli-course-resources
  importBucketName: dataimport

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: fxl_token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 3000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

wechat:
  request-url: https://api.weixin.qq.com/sns/jscode2session
  app-secret: 0ec180d59b9b076454e09a4fa4eff865
  app-id: wxf06ee34ae8ba2687
