server:
  port: 40000
run:
  schedule: true  # 设置为 true 以启动定时任务，设置为 false 则不运行
  oldDataSynchronizeStatus: true  # 开启旧系统同步
  checkLivingStatusScan: true  # 开启直播状态

scnu-cors:
  open: true

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  redis:
    host: 113.108.140.173
    port: 8001
    password: 12345A
  data:
    mongodb:
      uri: mongodb://scnuXueli:ScnuXueliDB2023@113.108.140.172:27017,113.108.140.174:27017,113.108.140.173:27017/scnuXueliDB?replicaSet=rs0

  # rabbitmq
  rabbitmq:
    host: 113.108.140.173
    port: 8003
    username: rabbitmq
    password: password
    queue1: data_synchronize
    queue2: test1
    queue3: data_export
    queue4: data_export2
    queue5: data_system_msg
    queue6: data_upload
    # 这个队列是用来发送操作消息给 CDN 服务
    cdn_queue1: cdn_file_operation1_alice
    # 这个队列是用来监听 CDN 服务发送过来的响应消息的
    cdn_queue2: cdn_file_operation1_blob

  servlet:
    multipart:
      maxFileSize: 10GB
      maxRequestSize: 10GB
  shardingsphere:
    # 属性配置
    props:
      # 显示修改以后的sql语句
      sql-show: true  # 是否打印sql
      sql-simple: true  # 打印简单的sql
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://113.108.140.172:3308/adult_education_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: xhl2023@
        hikari:
          maximum-pool-size: 2000 # 设置最大连接数为1000
          leakDetectionThreshold: 60000  # set to 60 seconds for example
          idleTimeout: 300000  # set to 5 minutes for example
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://113.108.140.173:3308/adult_education_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: xhl2023@
        hikari:
          maximum-pool-size: 2000 # 设置最大连接数为1000
          leakDetectionThreshold: 60000  # set to 60 seconds for example
          idleTimeout: 300000  # set to 5 minutes for example
    rules:
      readwrite-splitting:
        data-sources:
          mds: #名字自定义
            type: static #类型 静态获取
            props:
              auto-aware-data-source-name: master
              write-data-source-name: master

              read-data-source-names: master, slave  # 添加这两个才能平等读 否则只有 slave 在读
            load-balancer-name: read-random  #读写分离规则自定义命名
        load-balancers:
          read-random:
            type: ROUND_ROBIN # 轮询负载均衡

  elasticsearch:
    uris: 113.108.140.170
    port: 9200
    username: elastic
    password: elastic
    scheme: http
    index_name: es_xueli_index
    pipelineName: es_xueli_pipeline

#配置日志
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*xml
  type-aliases-package: com.scnujxjy.backendpoint.dao.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出到控制台
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 使用 SLF4J 和 Logback


# 设置日志输出
logging:
  config: logback.xml
  level:
    org.apache.ibatis: DEBUG
    com.scnujxjy.backendpoint.dao.mapper: DEBUG



minio:
  url: http://113.108.140.173:8000/
  accessKey: WU2D2LUC4BM0KHDLESAH
  secretKey: WkRxnF+X6icslZObAqT0xB6L6+yUQIMgMx082pDD
  bucketName: xuelistudentpictures
  courseCoverDir: xueli-course-resources
  importBucketName: dataimport

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: xl_token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 30000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false


# 开启 springboot exporter 能够被普罗米修斯监控到
management:
  server:
    port: 10056 # 管理端口
  endpoints:
    web:
      exposure:
        include: "prometheus" # 只在管理端口上暴露 Prometheus 端点
  metrics:
    export:
      prometheus:
        enabled: true

wechat:
  request-url: https://api.weixin.qq.com/sns/jscode2session
  app-secret: 0ec180d59b9b076454e09a4fa4eff865
  app-id: wxf06ee34ae8ba2687

knife4j:
  # 开启增强配置
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: scnuAdmin
    # Basic认证密码
    password: scnuAdmin2024@

#设置直播分类为2024学历教育520488。 510210是非学历培训，测试510211,默认分类486269
singleLiving:
  category: 520488