server:
  port: 40000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  redis:
    host: 113.108.140.173
    port: 8001
    password: 12345A
  # rabbitmq
  rabbitmq:
    host: 113.108.140.173
    port: 8003
    username: rabbitmq
    password: password
    queue1: data_synchronize
    queue2: test1
    queue3: data_export
    queue4: data_export2
    queue6: data_upload

  servlet:
    multipart:
      maxFileSize: 10GB
      maxRequestSize: 10GB
  ## mysql
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://113.108.140.172:3308/adult_education_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xhl2023@
    hikari:
      maximum-pool-size: 1000 # 设置最大连接数为1000
      leakDetectionThreshold: 60000  # set to 60 seconds for example
      idleTimeout: 300000  # set to 5 minutes for example

#配置日志
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*xml
  type-aliases-package: com.scnujxjy.backendpoint.dao.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出到控制台
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 使用 SLF4J 和 Logback

# 关闭 MyBatis 的日志
# 设置日志输出
logging:
  config: logback.xml



minio:
  url: http://113.108.140.173:8000/
  accessKey: WU2D2LUC4BM0KHDLESAH
  secretKey: WkRxnF+X6icslZObAqT0xB6L6+yUQIMgMx082pDD
  bucketName: xuelistudentpictures
  courseCoverDir: xueli-course-resources
  importBucketName: dataimport

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: xl_token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 30000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

wechat:
  request-url: https://api.weixin.qq.com/sns/jscode2session
  app-secret: 0ec180d59b9b076454e09a4fa4eff865
  app-id: wxf06ee34ae8ba2687


